name: Cypress Tests

on:
  push:
    branches-ignore:
      - "renovate/**"
      # - "!develop"

jobs:
  install:
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node16.14.2-slim-chrome103-ff102
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress install
        uses: cypress-io/github-action@v4
        with:
          runTests: false
      - run: yarn build:ci

      - name: Save build folder
        uses: actions/upload-artifact@v3
        with:
          name: build
          if-no-files-found: error
          path: build

  ui-chrome-tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node16.14.2-slim-chrome103-ff102
      options: --user 1001
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download the build folders
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build

      - name: "UI Tests - Chrome"
        uses: cypress-io/github-action@v4
        with:
          command-prefix: 'percy exec -- npx'
          start: yarn start:ci
          wait-on: "http://localhost:3000"
          wait-on-timeout: 120
          browser: chrome
          spec: cypress/tests/ui/*
        env:
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}

  # ui-chrome-mobile-tests:
  #   timeout-minutes: 15
  #   runs-on: ubuntu-latest
  #   container: 
  #     image: cypress/browsers:node16.14.2-slim-chrome103-ff102
  #     options: --user 1001
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       containers: [1, 2, 3, 4, 5]
  #   needs: install
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: Download the build folders
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: build
  #         path: build

  #     - name: "UI Tests - Chrome - Mobile"
  #       uses: cypress-io/github-action@v4
  #       with:
  #         config: "viewportWidth=375,viewportHeight=667"
  #         start: yarn start:ci
  #         wait-on: "http://localhost:3000"
  #         wait-on-timeout: 120
  #         browser: chrome
  #         record: true
  #         parallel: true
  #         group: 'UI - Chrome - Mobile'
  #         spec: cypress/tests/ui/*
  #       env:
  #         # Recommended: pass the GitHub token lets this action correctly
  #         # determine the unique run id necessary to re-run the checks
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

  ui-firefox-tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.14.2-slim-chrome103-ff102
      options: --user 1001
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download the build folders
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build

      - name: "UI Tests - Firefox"
        uses: cypress-io/github-action@v4
        with:
          start: yarn start:ci
          wait-on: "http://localhost:3000"
          wait-on-timeout: 120
          browser: firefox
          spec: cypress/tests/ui/*
        env:
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ui-firefox-mobile-tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.14.2-slim-chrome103-ff102
      options: --user 1001
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download the build folders
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build

      - name: "UI Tests - Firefox - Mobile"
        uses: cypress-io/github-action@v4
        with:
          config: "viewportWidth=375,viewportHeight=667"
          start: yarn start:ci
          wait-on: "http://localhost:3000"
          wait-on-timeout: 120
          browser: firefox
          spec: cypress/tests/ui/*
        env:
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  api-tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.14.2-slim-chrome103-ff102
      options: --user 1001
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download the build folders
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build

      - name: "API Tests"
        uses: cypress-io/github-action@v4
        with:
          start: yarn start:ci
          wait-on: "http://localhost:3000"
          wait-on-timeout: 120
          browser: firefox
          spec: cypress/tests/api/*
        env:
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ui-edge-tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
      options: --user 1001
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download the build folders
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build

      - name: "UI Tests - Edge"
        uses: cypress-io/github-action@v4
        with:
          start: yarn start:ci
          wait-on: "http://localhost:3000"
          wait-on-timeout: 120
          browser: edge
          spec: cypress/tests/ui/*
        env:
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

